modelname: basic_clip_repr
_target_: src.model.base_diffusion.MD

latent_dim: 512

ff_size: 1024
num_layers: 9
num_head: 8
droupout: 0.1
activation: "gelu"
render_vids_every_n_epochs: 100
num_vids_to_render: 2
lr_scheduler: null # cosine # null # reduceonplateau, steplr

zero_len_source: false
old_way: false
# normalization
statistics_path: ${statistics_path}
norm_type: standardize # min_max standardize
use_cls: True
use_repr: False
use_v_weight: True
source_align_coef: 0
target_align_coef: 0
cls_coef: 0.05
n_cls: 3
target_align_depth: 6

# diffusion related
diff_params:
  num_inference_timesteps: 200
  num_train_timesteps: 300
  prob_uncondp: 0.05 # 0.1 0.25
  prob_drop_text: 0.05 # 0.1 0.25
  prob_drop_motion: 0.05
  guidance_scale_text: 2.5 #
  guidance_scale_motion: 2.0
  noise_schedule: 'squaredcos_cap_v2' # Optional: ['linear', 'scaled_linear', 'squaredcos_cap_v2']
  predict_type: 'sample' # noise

motion_condition: source
source_encoder: null # trans_enc 
condition: text
smpl_path: ${data.smplh_path}
copy_target: false
nfeats: 135
dim_per_feat: [135]
# data related

input_feats:
# - "body_transl_delta"
- "body_transl_delta_pelv"
# - "body_transl_delta_pelv_xy_wo_z"
# - "body_transl_z"
# - "body_transl"
- "body_orient_xy"
- "z_orient_delta"
- "body_pose"
- "body_joints_local_wo_z_rot"
 
pad_inputs: false

loss_func_pos: mse # l1 mse
loss_func_feats: mse # l1 mse

defaults:
  # diffusion stuff
  - _self_
  - /path@path
  - train_scheduler: ddpm
  - infer_scheduler: ddpm
  - denoiser: ditdenoiser_cls_arch # ditdenoiser
  - text_encoder: clipenc_sim #clipenc #t5_enc  # distilbert_enc # t5_enc
  - motion_condition_encoder: actor
  - losses: basic
  - optim: adamw
  - /model/losses/function/recons@func_recons
  - /model/losses/function/recons@func_latent
  - /model/losses/function/kl@func_kl
