# name: distilbert_linear_encoder
_target_: src.model.textencoder.distilbert_encoder.DistilbertEncoderTransformer

latent_dim: ${model.latent_dim}

ff_size: ${model.ff_size}
num_layers: ${model.num_layers}
num_head: ${model.num_head}
droupout: ${model.droupout}
activation: ${model.activation}

finetune: false
modelpath: ${path.deps}/distilbert-base-uncased
