hydra:
  run:
    dir: .
  job:
    chdir: true
  output_subdir: null

folder: ???
mode: sample # denoise / sample / sthing else

prob_way: '3way' # 2way 

savedir: null
mean: false
fact: 1
number_of_samples: 1
ckpt_name: 'last'
last_ckpt_path: ${get_last_checkpoint:${folder},${ckpt_name}}
logger_level: INFO
save_pkl: false
render_vids: true
subset: null

num_sampling_steps: 1000

guidance_scale_text_n_motion: null
guidance_scale_motion: null

init_from: 'noise' # noise
condition_mode: 'full_cond' # 'mot_cond' 'text_cond'
inpaint: false
linear_gd: false

defaults:
  - _self_
  - data: motionfix
  - /path@path
  - override hydra/job_logging: rich # custom
  - override hydra/hydra_logging: rich # custom

split_to_load: 
- "test"
- "val"
