_target_: src.model.losses.MLDLosses

# Loss terms
## Reconstruction losses
lmd_rfeats_recons: 1.0
lmd_jfeats_recons: 1.0
predict_epsilon: false

modelname: ${model.modelname}

## Latent sinc. losses
lmd_latent: 1e-5
lmd_kl: 1e-5
lmd_prior: 0.0
lmd_recons: 1.0
lmd_gen: 1.0
fuse: 'concat' # 'add' null
# Ablations
loss_on_both: true
# loss on joint position features
loss_on_jfeats: false
ablation_no_kl_combine: false
ablation_no_kl_gaussian: false
ablation_no_motionencoder: false

# # Text => rfeats (rotation features)
# recons_text2rfeats: ${.lmd_rfeats_recons}
# recons_text2rfeats_func: ${model.func_recons}

# # Text => jfeats (xyz features)
# recons_text2jfeats: ${.lmd_jfeats_recons}
# recons_text2jfeats_func: ${model.func_recons}

# # rfeats => rfeats
# recons_rfeats2rfeats: ${.lmd_rfeats_recons}
# recons_rfeats2rfeats_func: ${model.func_recons}

# # vts => vts
# recons_vertex2vertex: ${.lmd_rfeats_recons}
# recons_vertex2vertex_func: ${model.func_recons}

# # jfeats => jfeats
# recons_jfeats2jfeats: ${.lmd_jfeats_recons}
# recons_jfeats2jfeats_func: ${model.func_recons}

# # Latent sinc.losses
# latent_manifold: ${.lmd_latent}
# latent_manifold_func: ${model.func_latent}

# # VAE losses
# kl_text: ${.lmd_kl}
# kl_text_func: ${model.func_kl}

# kl_motion: ${.lmd_kl}
# kl_motion_func: ${model.func_kl}

# kl_text2motion: ${.lmd_kl}
# kl_text2motion_func: ${model.func_kl}

# kl_motion2text: ${.lmd_kl}
# kl_motion2text_func: ${model.func_kl}

